# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Práticas de Campo e Mapeamento do Território
author: Mauro Alixandrini e Elaine Gomes de Jesus
logo: UFBA.png



# Information about where the book exists on the web
repository:
  url: https://github.com/Alixandrini/Mapeamento_Territorio  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true
